find_package(Boost REQUIRED serialization program_options filesystem)
find_package(OpenMP)
if (OPENMP_FOUND)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
endif ()

include_directories(${CMAKE_SOURCE_DIR})
include_directories(${CMAKE_SOURCE_DIR}/../../dependencies/sparsepp)
include_directories(${Boost_INCLUDE_DIRS})
include_directories(${CMAKE_SOURCE_DIR}/../../dependencies/include)
include_directories(${CMAKE_SOURCE_DIR}/../../dependencies/sparsehash-yche/include)
include_directories(${CMAKE_SOURCE_DIR}/../../dependencies/SFMT)
link_libraries(tcmalloc)
link_libraries(${CMAKE_THREAD_LIBS_INIT})
link_libraries(${Boost_LIBRARIES})
